### ISSUE TITLE
Troubles on update

### ISSUE THREAD

**Issue by whisher** [ahultgren/monguurl#1]
Hi,
sorry to bother you
and thanks for sharing :)
The module works fine on save 
but when I update a collection like

``` javascript
exports.post = function(req, res, next, id) {
    // http://stackoverflow.com/questions/14940660/whats-mongoose-error-cast-to-objectid-failed-for-value-xxx-at-path-id
    if (!/^[0-9a-fA-F]{24}$/.test(id)) {
        return res.jsonp(404,{ error: 'Failed to load post with id ' + id });
    }
    Post.findById(id).exec(function(err, post) {
        if (err) {
           return next(err);
        }
        if (!post) {
            return res.jsonp(404,{ error: 'Failed to load post with id ' + id });
        }
        req.post = post;
        next();
    });
};
/**
 * Update a post
 */
exports.update = function(req, res) {
    var post = req.post;
    post = _.extend(post, req.body);
    post.save(function(err) {
        if (err) {
            var errs = Object.keys(err.errors);
            if (errs.length > 0){
               return res.json(500,{ error: err.errors[errs[0]].message }); 
            }
            return res.json(500,{ error: 'Cannot save the post' });
        } 
        res.json(200,post);
    });
};
```

the slug don't get updated.

**Comment by ahultgren** [comment]
Hey, no problem at all :) It's just encouraging to see that someone actually uses this module.

It was a while since I wrote this though, so I'm not completely sure that what I'm about to say is correct. However, base on my vague memories and a quick glance at the code, it seems that I have not intended for monguurl to update the slug automatically when the document is updated. It kinda makes sense, since the primary usage would be url generation, which you normally don't want to change every time you edit the title.

The solution _should_ simply be to set `post.slug` to the new `post.title` (or whatever fields you're using) before each save. Like this:

``` javascript
exports.update = function(req, res) {
    var post = req.post;
    post = _.extend(post, req.body);

    // Update the target field here, monguurl will make sure it's urlified anew before save
    post.slug = post.title;

    post.save(function(err) {
        if (err) {
            var errs = Object.keys(err.errors);
            if (errs.length > 0){
               return res.json(500,{ error: err.errors[errs[0]].message }); 
            }
            return res.json(500,{ error: 'Cannot save the post' });
        } 
        res.json(200,post);
    });
};
```

Would that be a good enough solution and if so, could you try it and report back if it works or not? I'm unable to confirm it myself at the moment

**Comment by whisher** [comment]
It works fine :)
Thanks a ton.

BTW

> It kinda makes sense, since the primary usage would be url generation, which you normally don't want to change every time you edit the title.

Actually I was in two minds about this but you could think
of having mistaken the title but ..... I agree with you that
normally you don't want to change the url

I noticed just now that 
**stackoverflow**
do update the url when you change it
so ......

**Comment by ahultgren** [comment]
You're welcome :)

On SO the slug part of the url is actually not necessary at all (try removing it); only the id is used for finding the right post. The slug is probably only there for SEO purposes. If you look at Wordpress, Drupal and other common CMSes, they do not automatically update the slug, to avoid broken links. Thus I find the current behavior to be a sensible default.
